import {
  LeadStatus,
  OpportunityStatus,
} from "@/generated/prisma/client";

import { prisma } from "@/lib/prisma";

import type { PerformancePeriod } from "./staff-performance";

export type PerformanceDrilldownMetric =
  | "leads-generated"
  | "qualified-leads"
  | "opportunities-created"
  | "opportunities-won"
  | "opportunities-lost"
  | "open-opportunities"
  | "activities";

export type PerformanceDrilldownRecord = {
  id: string;
  type:
    | "lead"
    | "opportunity"
    | "activity";
  title: string;
  subtitle: string | null;
  status: string | null;
  value: number | null;
  createdAt: Date;
  closedAt: Date | null;
};

export type PerformanceDrilldownResult = {
  metric: PerformanceDrilldownMetric;
  records: PerformanceDrilldownRecord[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
};

const DEFAULT_PAGE_SIZE = 25;
const MAX_PAGE_SIZE = 100;

function normalizePagination(
  page: number,
  pageSize: number,
) {
  const normalizedPage =
    Number.isFinite(page) && page > 0
      ? Math.floor(page)
      : 1;

  const normalizedPageSize =
    Number.isFinite(pageSize) && pageSize > 0
      ? Math.min(
          Math.floor(pageSize),
          MAX_PAGE_SIZE,
        )
      : DEFAULT_PAGE_SIZE;

  return {
    page: normalizedPage,
    pageSize: normalizedPageSize,
  };
}

function getDateRangeFilter(
  period: PerformancePeriod,
) {
  return {
    gte: period.from,
    lt: period.to,
  };
}

function toNumber(
  value:
    | {
        toNumber(): number;
      }
    | number
    | null,
): number | null {
  if (value === null) {
    return null;
  }

  return typeof value === "number"
    ? value
    : value.toNumber();
}

function assignmentCoversTimestamp(
  assignment: {
    assignedAt: Date;
    unassignedAt: Date | null;
  },
  timestamp: Date,
): boolean {
  return (
    assignment.assignedAt <= timestamp &&
    (
      assignment.unassignedAt === null ||
      assignment.unassignedAt > timestamp
    )
  );
}

/**
 * Return leads generated by a staff member
 * during the selected performance period.
 *
 * Attribution is based on the user who created
 * the lead, not its current owner.
 */
async function getGeneratedLeads(
  userId: string,
  period: PerformancePeriod,
  page: number,
  pageSize: number,
): Promise<PerformanceDrilldownResult> {
  const dateRange =
    getDateRangeFilter(period);

  const where = {
    createdByUserId: userId,
    createdAt: dateRange,
  };

  const [total, leads] =
    await Promise.all([
      prisma.lead.count({
        where,
      }),

      prisma.lead.findMany({
        where,
        select: {
          id: true,
          status: true,
          createdAt: true,
          organization: {
            select: {
              name: true,
            },
          },
          contact: {
            select: {
              name: true,
            },
          },
        },
        orderBy: {
          createdAt: "desc",
        },
        skip:
          (page - 1) * pageSize,
        take: pageSize,
      }),
    ]);

  return {
    metric: "leads-generated",
    records: leads.map((lead) => ({
      id: lead.id,
      type: "lead",
      title:
        lead.organization.name,
      subtitle:
        lead.contact?.name ?? null,
      status: lead.status,
      value: null,
      createdAt: lead.createdAt,
      closedAt: null,
    })),
    total,
    page,
    pageSize,
    totalPages:
      Math.ceil(total / pageSize),
  };
}

/**
 * Return leads counted as qualified by the
 * existing staff-performance service.
 *
 * Qualification remains based on current lead
 * status because Lead does not yet have status history.
 */
async function getQualifiedLeads(
  userId: string,
  period: PerformancePeriod,
  page: number,
  pageSize: number,
): Promise<PerformanceDrilldownResult> {
  const dateRange =
    getDateRangeFilter(period);

  const qualifiedStatuses: LeadStatus[] = [
    LeadStatus.QUALIFIED,
    LeadStatus.DISCOVERY,
    LeadStatus.PROPOSAL_SENT,
    LeadStatus.NEGOTIATION,
    LeadStatus.WON,
  ];

  const where = {
    createdByUserId: userId,
    createdAt: dateRange,
    status: {
      in: qualifiedStatuses,
    },
  };

  const [total, leads] =
    await Promise.all([
      prisma.lead.count({
        where,
      }),

      prisma.lead.findMany({
        where,
        select: {
          id: true,
          status: true,
          createdAt: true,
          organization: {
            select: {
              name: true,
            },
          },
          contact: {
            select: {
              name: true,
            },
          },
        },
        orderBy: {
          createdAt: "desc",
        },
        skip:
          (page - 1) * pageSize,
        take: pageSize,
      }),
    ]);

  return {
    metric: "qualified-leads",
    records: leads.map((lead) => ({
      id: lead.id,
      type: "lead",
      title:
        lead.organization.name,
      subtitle:
        lead.contact?.name ?? null,
      status: lead.status,
      value: null,
      createdAt: lead.createdAt,
      closedAt: null,
    })),
    total,
    page,
    pageSize,
    totalPages:
      Math.ceil(total / pageSize),
  };
}

/**
 * Return opportunities created by a staff member
 * during the selected period.
 *
 * Attribution is based on createdByUserId.
 */
async function getCreatedOpportunities(
  userId: string,
  period: PerformancePeriod,
  page: number,
  pageSize: number,
): Promise<PerformanceDrilldownResult> {
  const dateRange =
    getDateRangeFilter(period);

  const where = {
    createdByUserId: userId,
    createdAt: dateRange,
  };

  const [total, opportunities] =
    await Promise.all([
      prisma.opportunity.count({
        where,
      }),

      prisma.opportunity.findMany({
        where,
        select: {
          id: true,
          name: true,
          description: true,
          status: true,
          estimatedValue: true,
          createdAt: true,
          closedAt: true,
          auditRequest: {
            select: {
              organization: {
                select: {
                  name: true,
                },
              },
            },
          },
        },
        orderBy: {
          createdAt: "desc",
        },
        skip:
          (page - 1) * pageSize,
        take: pageSize,
      }),
    ]);

  return {
    metric: "opportunities-created",
    records: opportunities.map(
      (opportunity) => ({
        id: opportunity.id,
        type: "opportunity",
        title: opportunity.name,
        subtitle:
          opportunity.auditRequest
            .organization.name,
        status: opportunity.status,
        value: toNumber(
          opportunity.estimatedValue,
        ),
        createdAt:
          opportunity.createdAt,
        closedAt:
          opportunity.closedAt,
      }),
    ),
    total,
    page,
    pageSize,
    totalPages:
      Math.ceil(total / pageSize),
  };
}

/**
 * Return opportunities won by a staff member
 * during the selected period.
 *
 * The performance date is closedAt.
 * Ownership is determined from assignment history
 * at the exact close timestamp.
 */
async function getWonOpportunities(
  userId: string,
  period: PerformancePeriod,
  page: number,
  pageSize: number,
): Promise<PerformanceDrilldownResult> {
  const dateRange =
    getDateRangeFilter(period);

  const where = {
    closedAt: dateRange,
    status: "WON" as const,
  };

  const [allMatching,] =
    await Promise.all([
      prisma.opportunity.findMany({
        where,
        select: {
          id: true,
          name: true,
          description: true,
          status: true,
          estimatedValue: true,
          createdAt: true,
          closedAt: true,
          assignments: {
            select: {
              assignedToUserId: true,
              assignedAt: true,
              unassignedAt: true,
            },
            orderBy: {
              assignedAt: "asc",
            },
          },
          auditRequest: {
            select: {
              organization: {
                select: {
                  name: true,
                },
              },
            },
          },
        },
        orderBy: {
          closedAt: "desc",
        },
      }),
    ]);

  const matching = allMatching.filter(
    (opportunity) => {
      const closedAt = opportunity.closedAt;

      if (!closedAt) {
        return false;
      }

      return opportunity.assignments.some(
        (assignment) =>
          assignment.assignedToUserId === userId &&
          assignmentCoversTimestamp(
            assignment,
            closedAt,
          ),
      );
    },
  );

  const total = matching.length;

  const opportunities = matching.slice(
    (page - 1) * pageSize,
    page * pageSize,
  );

  return {
    metric: "opportunities-won",
    records: opportunities.map(
      (opportunity) => ({
        id: opportunity.id,
        type: "opportunity",
        title: opportunity.name,
        subtitle:
          opportunity.auditRequest
            .organization.name,
        status: opportunity.status,
        value: toNumber(
          opportunity.estimatedValue,
        ),
        createdAt:
          opportunity.createdAt,
        closedAt:
          opportunity.closedAt,
      }),
    ),
    total,
    page,
    pageSize,
    totalPages:
      Math.ceil(total / pageSize),
  };
}

/**
 * Return opportunities lost by a staff member
 * during the selected period.
 *
 * The performance date is closedAt.
 * Ownership is determined from assignment history
 * at the exact close timestamp.
 */
async function getLostOpportunities(
  userId: string,
  period: PerformancePeriod,
  page: number,
  pageSize: number,
): Promise<PerformanceDrilldownResult> {
  const dateRange =
    getDateRangeFilter(period);

  const where = {
    closedAt: dateRange,
    status: "LOST" as const,
  };

  const allMatching =
    await prisma.opportunity.findMany({
      where,
      select: {
        id: true,
        name: true,
        description: true,
        status: true,
        estimatedValue: true,
        createdAt: true,
        closedAt: true,
        assignments: {
          select: {
            assignedToUserId: true,
            assignedAt: true,
            unassignedAt: true,
          },
          orderBy: {
            assignedAt: "asc",
          },
        },
        auditRequest: {
          select: {
            organization: {
              select: {
                name: true,
              },
            },
          },
        },
      },
      orderBy: {
        closedAt: "desc",
      },
    });

  const matching = allMatching.filter(
    (opportunity) => {
      const closedAt = opportunity.closedAt;

      if (!closedAt) {
        return false;
      }

      return opportunity.assignments.some(
        (assignment) =>
          assignment.assignedToUserId === userId &&
          assignmentCoversTimestamp(
            assignment,
            closedAt,
          ),
      );
    },
  );

  const total = matching.length;

  const opportunities = matching.slice(
    (page - 1) * pageSize,
    page * pageSize,
  );

  return {
    metric: "opportunities-lost",
    records: opportunities.map(
      (opportunity) => ({
        id: opportunity.id,
        type: "opportunity",
        title: opportunity.name,
        subtitle:
          opportunity.auditRequest
            .organization.name,
        status: opportunity.status,
        value: toNumber(
          opportunity.estimatedValue,
        ),
        createdAt:
          opportunity.createdAt,
        closedAt:
          opportunity.closedAt,
      }),
    ),
    total,
    page,
    pageSize,
    totalPages:
      Math.ceil(total / pageSize),
  };
}

/**
 * Return opportunities that were open at the
 * end of the selected performance period.
 *
 * Ownership is determined from assignment history
 * at period.to.
 */
async function getOpenOpportunities(
  userId: string,
  period: PerformancePeriod,
  page: number,
  pageSize: number,
): Promise<PerformanceDrilldownResult> {
  const where = {
    createdAt: {
      lt: period.to,
    },
    OR: [
      {
        closedAt: null,
      },
      {
        closedAt: {
          gte: period.to,
        },
      },
    ],
    status: {
      notIn: [
        OpportunityStatus.WON,
        OpportunityStatus.LOST,
      ],
    },
  };

  const allMatching =
    await prisma.opportunity.findMany({
      where,
      select: {
        id: true,
        name: true,
        description: true,
        status: true,
        estimatedValue: true,
        createdAt: true,
        closedAt: true,
        assignments: {
          select: {
            assignedToUserId: true,
            assignedAt: true,
            unassignedAt: true,
          },
          orderBy: {
            assignedAt: "asc",
          },
        },
        auditRequest: {
          select: {
            organization: {
              select: {
                name: true,
              },
            },
          },
        },
      },
      orderBy: {
        createdAt: "desc",
      },
    });

  const matching = allMatching.filter(
    (opportunity) =>
      opportunity.assignments.some(
        (assignment) =>
          assignment.assignedToUserId === userId &&
          assignmentCoversTimestamp(
            assignment,
            period.to,
          ),
      ),
  );

  const total = matching.length;

  const opportunities = matching.slice(
    (page - 1) * pageSize,
    page * pageSize,
  );

  return {
    metric: "open-opportunities",
    records: opportunities.map(
      (opportunity) => ({
        id: opportunity.id,
        type: "opportunity",
        title: opportunity.name,
        subtitle:
          opportunity.auditRequest
            .organization.name,
        status: opportunity.status,
        value: toNumber(
          opportunity.estimatedValue,
        ),
        createdAt:
          opportunity.createdAt,
        closedAt:
          opportunity.closedAt,
      }),
    ),
    total,
    page,
    pageSize,
    totalPages:
      Math.ceil(total / pageSize),
  };
}

/**
 * Return activities created by a staff member
 * during the selected period.
 */
async function getActivities(
  userId: string,
  period: PerformancePeriod,
  page: number,
  pageSize: number,
): Promise<PerformanceDrilldownResult> {
  const dateRange =
    getDateRangeFilter(period);

  const where = {
    createdByUserId: userId,
    createdAt: dateRange,
  };

  const [total, activities] =
    await Promise.all([
      prisma.activity.count({
        where,
      }),

      prisma.activity.findMany({
        where,
        select: {
          id: true,
          type: true,
          description: true,
          createdAt: true,
          organization: {
            select: {
              name: true,
            },
          },
        },
        orderBy: {
          createdAt: "desc",
        },
        skip:
          (page - 1) * pageSize,
        take: pageSize,
      }),
    ]);

  return {
    metric: "activities",
    records: activities.map(
      (activity) => ({
        id: activity.id,
        type: "activity",
        title: activity.type,
        subtitle:
          activity.organization.name,
        status: null,
        value: null,
        createdAt: activity.createdAt,
        closedAt: null,
      }),
    ),
    total,
    page,
    pageSize,
    totalPages:
      Math.ceil(total / pageSize),
  };
}

export async function getStaffPerformanceDrilldown(
  userId: string,
  metric: PerformanceDrilldownMetric,
  period: PerformancePeriod,
  page = 1,
  pageSize = DEFAULT_PAGE_SIZE,
): Promise<PerformanceDrilldownResult> {
  const pagination =
    normalizePagination(
      page,
      pageSize,
    );

  switch (metric) {
    case "leads-generated":
      return getGeneratedLeads(
        userId,
        period,
        pagination.page,
        pagination.pageSize,
      );

    case "qualified-leads":
      return getQualifiedLeads(
        userId,
        period,
        pagination.page,
        pagination.pageSize,
      );

    case "opportunities-created":
      return getCreatedOpportunities(
        userId,
        period,
        pagination.page,
        pagination.pageSize,
      );

    case "opportunities-won":
      return getWonOpportunities(
        userId,
        period,
        pagination.page,
        pagination.pageSize,
      );

    case "opportunities-lost":
      return getLostOpportunities(
        userId,
        period,
        pagination.page,
        pagination.pageSize,
      );

    case "open-opportunities":
      return getOpenOpportunities(
        userId,
        period,
        pagination.page,
        pagination.pageSize,
      );

    case "activities":
      return getActivities(
        userId,
        period,
        pagination.page,
        pagination.pageSize,
      );
  }
}